# Generated by Django 5.0.6 on 2024-06-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_customuser_address_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
